server:
  port: 8896

spring:
  application:
    name: richtext-wangeditor
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    mode: html
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ourschool?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000 # 单位是毫秒
      time-between-eviction-runs-millis: 60000  # 这个下面的不配置也是可以的, 不配置就不用去写druid的config, 也没有对应监控功能
      min-evictable-idle-time-millis: 300000 # 这个下面的不配置也是可以的, 不配置就不用去写druid的config, 也没有对应监控功能
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      maxPoolPreparedStatementPerConnectionSize: 20
      seGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false # mybatis关闭了驼峰转下划线
  mapper-locations: classpath:com/zgy/learn/richtextwangeditor/mapper/*.xml # mapper文件的位置, 使用接口和注解查询其实更好
  type-aliases-package: com.zgy.learn.richtextwangeditor.pojo # 返回结果类型的时候, 可以直接使用类名

# log位置的配置
logging:
  file:
    path: /web/tomcat/logs/richtext-wangeditor